version: '3.7'

services: 
  web:
    image: "${TELEMEDICINE_IMAGE}"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes: 
        - static_volume:/usr/src/app/static
    ports:
        - 8001:8000
    env_file: 
        - ./.env.prod
  
  db:
    image: postgres:12.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=telemedicine
      - POSTGRES_PASSWORD=LocalPassword
      - POSTGRES_DB=telemedicine_db


volumes: 
    static_volume:
    postgres_data:
